# Generated by Django 6.0.5 on 2026-06-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsize',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
